### ISSUE TITLE
Hosting your dataset on the Hugging Face Hub

### ISSUE THREAD

**Issue by lewtun** [gururise/AlpacaDataCleaned#13]
Hi @gururise, this is a really cool project and great job identifying all these problems with the Alpaca dataset!

Would you be interested in hosting this on the Hugging Face Hub (https://huggingface.co/datasets)? The Alpaca dataset is also hosted there ([link](https://huggingface.co/datasets/tatsu-lab/alpaca)) and your version would be of wide interest to the community :)

If that sounds interesting, you just need to create a new dataset repo and upload your `alpaca_cleaned.json` file through the UI. For more details, you can check out our docs [here](https://huggingface.co/docs/datasets/upload_dataset)

**Comment by gururise** [comment]
Thanks! Been meaning to do this! Will get this uploaded to the hub soon.

**Comment by gururise** [comment]
https://huggingface.co/datasets/yahma/alpaca-cleaned

**Comment by lewtun** [comment]
That was quick, thanks! Closing this issue now :)
