### ISSUE TITLE
Idea about better cleaning

### ISSUE THREAD

**Issue by xor2003** [gururise/AlpacaDataCleaned#18]
1. Probably need to move cleaned data from one file to another so no need to check again  and again.
2. For one other model guys prepared Telegram bot. So people could read random Question/Answer and choose button:

- Everything correct
- Wrong question
- Wrong answer
- Skip it

Maybe make sense to get duplicate confirmations...

**Comment by gururise** [comment]
> 1. Probably need to move cleaned data from one file to another so no need to check again  and again.
> 
>     2. For one other model guys prepared Telegram bot. So people could read random Question/Answer and choose button:
> 
> 
>     * Everything correct
> 
>     * Wrong question
> 
>     * Wrong answer
> 
>     * Skip it
> 
> 
> Maybe make sense to get duplicate confirmations...

Not a bad idea. Maybe a web interface where people could view the dataset and suggest changes.

**Comment by xor2003** [comment]
+ CI CD check for correct json

**Comment by gururise** [comment]
> * CI CD check for correct json

CI CD check for valid JSON done
