### ISSUE TITLE
Adding scripts for data cleaning

### ISSUE THREAD

**Issue by thisserand** [gururise/AlpacaDataCleaned#2]
Thanks for your work! Did you make the changes primarily by manually examining the dataset? If scripts were used for the cleanup, it might be helpful for others to have access to those scripts as well. I am in the process of creating a dataset for the German language using GPT and will likely run into similar issues. So it would be nice to be able to access these scripts. I'm sure you understand where I'm going with this. What are your thoughts on this? I know it's not straightforward, because when I cleaned up the lists, it was also a combination of using Regex and manually monitoring the changes.

**Comment by gururise** [comment]
Mostly manual with some regex.  @HideLord [shared](https://github.com/gururise/AlpacaDataCleaned/pull/3) a very useful regex for identifying math instructions.

I'll clean up and upload the scripts I've been using to identify/solve issues.

**Comment by thisserand** [comment]
Okay, thank you!

**Comment by gururise** [comment]
Add tool used for "input" field checking in 25e265ac53fe5e91325ef5b7e9d2ae1eced293fb
