### ISSUE TITLE
80% of math outputs are wrong

### ISSUE THREAD

**Issue by gururise** [gururise/AlpacaDataCleaned#4]
As noted in PR #3, many math outputs are incorrect (estimated at nearly 80% by @HideLord).  Ideally, anyone wants to work these issues should follow the same format:

Original Wrong Answer:
```        
"instruction": "Calculate the median of the following data set.",
"input": "1, 2, 4, 5, 8, 9",
"output": "5"
```

Corrected Answer (with [Chain of Thought](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgVgTjwA0IzKekrQoMziCmDXjO10QKjdDdzK1Oj8bZToPOI6VjVzTKXZ6vnWvAGOdVnWznJK2ZZjfBuTLojobayI_yrvlFzE3dCErF2j5wKLGFWAkuGP9-r-hMrqFivnjYhbCIu7HFINSmHu4wUjlKHfJxWHZ8Y7CYUowWvxTeRJhQEAUswGh2fUd3VHA/s2500/chainofthought.png)):
```
"instruction": "Calculate the median of the following data set.",
"input": "1, 2, 4, 5, 8, 9",
"output": "The median is (4+5)/2 = 4.5"
```

To identify math problems, one can use the regex provided:
`"input": "([\d\^\+\-\/yx=,\(\) ]|\\u00b\d)+"`

Modifying an existing tool script (in the tools directory) to use this regex would be easy. The first 200 math questions have been checked in the above PR.

**Comment by xor2003** [comment]
Maybe make sense to teach it generate request to mathmatical packets like python or maxima?
```
<external>
#!/usr/bin/env python
array = [1, 2, 4, 5, 8, 9]
print(sum(array)/len(array))
```
Detect <external> and execute
