### ISSUE TITLE
Contributing to the dataset curation with Argilla and the Alpaca Garbage collector

### ISSUE THREAD

**Issue by dvsrepo** [gururise/AlpacaDataCleaned#53]
Hi @gururise, first of all, thanks and congrats on this important effort.

I'm Dani from [Argilla](https://github.com/argilla-io/argilla). We've spent some time looking at data quality issues of the Alpaca dataset and its translations. We're helping out teams of the Spanish and German efforts to use Argilla for flagging bad or problematic instructions so that they can be later fixed (either manually or with post-processing).

Along the way, we've spent some time labeling AlpacaDataCleaned. It has already good quality but there are still examples to improve, so we'd like to contribute.

Today we have released this model to help teams with cleaning up Alpaca translation, but this can be used to contribute to this repo too: https://huggingface.co/argilla/alpaca-garbage-collector-multilingual

We've also deployed this space for browsing and validating the records. This is [what it shows](https://argilla-alpaca-hallucihunter.hf.space/datasets/team/alpaca-cleaned-english?query=eyJwcmVkaWN0ZWRfYXMiOlsiQkFEIElOU1RSVUNUSU9OIl0sIm1ldGFkYXRhIjp7fX0&sort=W3sia2V5Ijoic2NvcmUiLCJuYW1lIjoiU2NvcmUiLCJ0eXBlIjoic2NvcmUiLCJncm91cCI6IlByZWRpY3Rpb25zIiwiaWQiOiJzY29yZSIsIm9wdGlvbnMiOnsiMC41IjoxLCIwLjUwMSI6MiwiMC41MDIiOjEsIjAuNTAzIjoyLCIwLjUwNCI6MSwiMC41MDUiOjIsIjAuNTA2Ijo0LCIwLjUwNyI6MCwiMC41MDgiOjEsIjAuNTA5IjoyLCIwLjUxIjoyLCIwLjUxMSI6MSwiMC41MTIiOjAsIjAuNTEzIjozLCIwLjUxNCI6MywiMC41MTUiOjAsIjAuNTE2IjoxLCIwLjUxNyI6MywiMC41MTgiOjIsIjAuNTE5IjowLCIwLjUyIjozLCIwLjUyMSI6MywiMC41MjIiOjEsIjAuNTIzIjoyLCIwLjUyNCI6MywiMC41MjUiOjEsIjAuNTI2IjoyLCIwLjUyNyI6MywiMC41MjgiOjIsIjAuNTI5IjoyLCIwLjUzIjowLCIwLjUzMSI6MSwiMC41MzIiOjMsIjAuNTMzIjowLCIwLjUzNCI6MSwiMC41MzUiOjIsIjAuNTM2IjozLCIwLjUzNyI6MiwiMC41MzgiOjAsIjAuNTM5IjowLCIwLjU0IjoxLCIwLjU0MSI6MSwiMC41NDIiOjMsIjAuNTQzIjoxLCIwLjU0NCI6MCwiMC41NDUiOjAsIjAuNTQ2IjoxLCIwLjU0NyI6MSwiMC41NDgiOjQsIjAuNTQ5IjozLCIwLjU1IjoxLCIwLjU1MSI6MSwiMC41NTIiOjIsIjAuNTUzIjoyLCIwLjU1NCI6MywiMC41NTUiOjIsIjAuNTU2IjoxLCIwLjU1NyI6NCwiMC41NTgiOjMsIjAuNTU5IjoxLCIwLjU2IjoyLCIwLjU2MSI6MywiMC41NjIiOjEsIjAuNTYzMDAwMDAwMDAwMDAwMSI6MiwiMC41NjQwMDAwMDAwMDAwMDAxIjoxLCIwLjU2NTAwMDAwMDAwMDAwMDEiOjEsIjAuNTY2MDAwMDAwMDAwMDAwMSI6MiwiMC41NjcwMDAwMDAwMDAwMDAxIjowLCIwLjU2ODAwMDAwMDAwMDAwMDEiOjQsIjAuNTY5MDAwMDAwMDAwMDAwMSI6MiwiMC41NzAwMDAwMDAwMDAwMDAxIjoyLCIwLjU3MTAwMDAwMDAwMDAwMDEiOjIsIjAuNTcyMDAwMDAwMDAwMDAwMSI6MiwiMC41NzMwMDAwMDAwMDAwMDAxIjoyLCIwLjU3NDAwMDAwMDAwMDAwMDEiOjIsIjAuNTc1MDAwMDAwMDAwMDAwMSI6MywiMC41NzYwMDAwMDAwMDAwMDAxIjo2LCIwLjU3NyI6MywiMC41NzgiOjIsIjAuNTc5IjoyLCIwLjU4IjozLCIwLjU4MSI6NywiMC41ODIiOjIsIjAuNTgzIjo0LCIwLjU4NCI6NCwiMC41ODUiOjEsIjAuNTg2Ijo1LCIwLjU4NyI6NCwiMC41ODgiOjAsIjAuNTg5IjoxLCIwLjU5IjozLCIwLjU5MSI6MiwiMC41OTIiOjMsIjAuNTkzIjozLCIwLjU5NCI6MiwiMC41OTUiOjAsIjAuNTk2Ijo0LCIwLjU5NyI6MCwiMC41OTgiOjQsIjAuNTk5IjoyLCIwLjYiOjIsIjAuNjAxIjozLCIwLjYwMiI6MSwiMC42MDMiOjIsIjAuNjA0Ijo0LCIwLjYwNSI6NCwiMC42MDYiOjMsIjAuNjA3IjoyLCIwLjYwOCI6MSwiMC42MDkiOjUsIjAuNjEiOjQsIjAuNjExIjoxLCIwLjYxMiI6MSwiMC42MTMiOjIsIjAuNjE0IjowLCIwLjYxNSI6MSwiMC42MTYiOjIsIjAuNjE3Ijo1LCIwLjYxOCI6MywiMC42MTkiOjAsIjAuNjIiOjIsIjAuNjIxIjoyLCIwLjYyMiI6MywiMC42MjMiOjEsIjAuNjI0IjowLCIwLjYyNSI6MSwiMC42MjYiOjMsIjAuNjI3IjozLCIwLjYyOCI6MSwiMC42MjkiOjEsIjAuNjMiOjIsIjAuNjMxIjoyLCIwLjYzMiI6MiwiMC42MzMiOjQsIjAuNjM0IjoxLCIwLjYzNSI6NSwiMC42MzYiOjIsIjAuNjM3IjozLCIwLjYzOCI6MCwiMC42MzkiOjUsIjAuNjQiOjEsIjAuNjQxIjoxLCIwLjY0MiI6MiwiMC42NDMiOjMsIjAuNjQ0IjozLCIwLjY0NSI6NCwiMC42NDYiOjAsIjAuNjQ3Ijo0LCIwLjY0OCI6NCwiMC42NDkiOjAsIjAuNjUiOjIsIjAuNjUxIjoyLCIwLjY1MiI6MiwiMC42NTMiOjEsIjAuNjU0IjoyLCIwLjY1NSI6MywiMC42NTYiOjIsIjAuNjU3IjoyLCIwLjY1OCI6MSwiMC42NTkiOjEsIjAuNjYiOjQsIjAuNjYxIjozLCIwLjY2MiI6MCwiMC42NjMiOjMsIjAuNjY0IjowLCIwLjY2NSI6MywiMC42NjYiOjAsIjAuNjY3Ijo2LCIwLjY2OCI6MSwiMC42NjkiOjMsIjAuNjciOjEsIjAuNjcxIjoyLCIwLjY3MiI6MiwiMC42NzMiOjIsIjAuNjc0Ijo1LCIwLjY3NSI6MywiMC42NzYiOjIsIjAuNjc3Ijo1LCIwLjY3OCI6MCwiMC42NzkiOjMsIjAuNjgiOjYsIjAuNjgxIjoxLCIwLjY4MiI6MCwiMC42ODMiOjEsIjAuNjg0IjozLCIwLjY4NSI6MiwiMC42ODYiOjMsIjAuNjg3IjoyLCIwLjY4ODAwMDAwMDAwMDAwMDEiOjQsIjAuNjg5MDAwMDAwMDAwMDAwMSI6NCwiMC42OTAwMDAwMDAwMDAwMDAxIjoyLCIwLjY5MTAwMDAwMDAwMDAwMDEiOjMsIjAuNjkyMDAwMDAwMDAwMDAwMSI6NCwiMC42OTMwMDAwMDAwMDAwMDAxIjozLCIwLjY5NDAwMDAwMDAwMDAwMDEiOjQsIjAuNjk1MDAwMDAwMDAwMDAwMSI6MiwiMC42OTYwMDAwMDAwMDAwMDAxIjoxLCIwLjY5NzAwMDAwMDAwMDAwMDEiOjIsIjAuNjk4MDAwMDAwMDAwMDAwMSI6MiwiMC42OTkwMDAwMDAwMDAwMDAxIjozLCIwLjcwMDAwMDAwMDAwMDAwMDEiOjUsIjAuNzAxMDAwMDAwMDAwMDAwMSI6NiwiMC43MDIwMDAwMDAwMDAwMDAxIjowLCIwLjcwMzAwMDAwMDAwMDAwMDEiOjUsIjAuNzA0IjoyLCIwLjcwNSI6MSwiMC43MDYiOjIsIjAuNzA3IjoxLCIwLjcwOCI6MiwiMC43MDkiOjAsIjAuNzEiOjEsIjAuNzExIjozLCIwLjcxMiI6NCwiMC43MTMiOjEsIjAuNzE0Ijo0LCIwLjcxNSI6MCwiMC43MTYiOjEsIjAuNzE3IjozLCIwLjcxOCI6MSwiMC43MTkiOjMsIjAuNzIiOjEsIjAuNzIxIjowLCIwLjcyMiI6NCwiMC43MjMiOjIsIjAuNzI0Ijo0LCIwLjcyNSI6NSwiMC43MjYiOjQsIjAuNzI3IjoxLCIwLjcyOCI6MCwiMC43MjkiOjIsIjAuNzMiOjQsIjAuNzMxIjoxLCIwLjczMiI6MiwiMC43MzMiOjMsIjAuNzM0IjowLCIwLjczNSI6NSwiMC43MzYiOjMsIjAuNzM3IjoyLCIwLjczOCI6NCwiMC43MzkiOjUsIjAuNzQiOjMsIjAuNzQxIjowLCIwLjc0MiI6MiwiMC43NDMiOjEsIjAuNzQ0IjoxLCIwLjc0NSI6MywiMC43NDYiOjMsIjAuNzQ3IjoyLCIwLjc0OCI6MiwiMC43NDkiOjMsIjAuNzUiOjIsIjAuNzUxIjoyLCIwLjc1MiI6MiwiMC43NTMiOjAsIjAuNzU0IjoyLCIwLjc1NSI6MSwiMC43NTYiOjYsIjAuNzU3IjozLCIwLjc1OCI6MywiMC43NTkiOjIsIjAuNzYiOjUsIjAuNzYxIjo2LCIwLjc2MiI6MSwiMC43NjMiOjIsIjAuNzY0IjozLCIwLjc2NSI6NCwiMC43NjYiOjQsIjAuNzY3IjoxLCIwLjc2OCI6MSwiMC43NjkiOjQsIjAuNzciOjUsIjAuNzcxIjozLCIwLjc3MiI6NSwiMC43NzMiOjIsIjAuNzc0IjozLCIwLjc3NSI6MiwiMC43NzYiOjAsIjAuNzc3IjozLCIwLjc3OCI6MSwiMC43NzkiOjQsIjAuNzgiOjMsIjAuNzgxIjo0LCIwLjc4MiI6NSwiMC43ODMiOjEsIjAuNzg0IjowLCIwLjc4NSI6MiwiMC43ODYiOjUsIjAuNzg3Ijo2LCIwLjc4OCI6MywiMC43ODkiOjYsIjAuNzkiOjIsIjAuNzkxIjoxLCIwLjc5MiI6NCwiMC43OTMiOjIsIjAuNzk0IjoyLCIwLjc5NSI6MywiMC43OTYiOjMsIjAuNzk3IjozLCIwLjc5OCI6MSwiMC43OTkiOjQsIjAuOCI6NCwiMC44MDEiOjYsIjAuODAyIjo1LCIwLjgwMyI6NSwiMC44MDQiOjcsIjAuODA1IjoyLCIwLjgwNiI6MiwiMC44MDciOjUsIjAuODA4IjozLCIwLjgwOSI6NCwiMC44MSI6MiwiMC44MTEiOjMsIjAuODEyIjozLCIwLjgxMzAwMDAwMDAwMDAwMDEiOjUsIjAuODE0MDAwMDAwMDAwMDAwMSI6MiwiMC44MTUwMDAwMDAwMDAwMDAxIjoyLCIwLjgxNjAwMDAwMDAwMDAwMDEiOjQsIjAuODE3MDAwMDAwMDAwMDAwMSI6NywiMC44MTgwMDAwMDAwMDAwMDAxIjoyLCIwLjgxOTAwMDAwMDAwMDAwMDEiOjAsIjAuODIwMDAwMDAwMDAwMDAwMSI6MSwiMC44MjEwMDAwMDAwMDAwMDAxIjozLCIwLjgyMjAwMDAwMDAwMDAwMDEiOjEsIjAuODIzMDAwMDAwMDAwMDAwMSI6MSwiMC44MjQwMDAwMDAwMDAwMDAxIjo2LCIwLjgyNTAwMDAwMDAwMDAwMDEiOjIsIjAuODI2MDAwMDAwMDAwMDAwMSI6NCwiMC44MjcwMDAwMDAwMDAwMDAxIjozLCIwLjgyODAwMDAwMDAwMDAwMDEiOjEsIjAuODI5MDAwMDAwMDAwMDAwMSI6MSwiMC44MzAwMDAwMDAwMDAwMDAxIjo4LCIwLjgzMTAwMDAwMDAwMDAwMDEiOjMsIjAuODMyMDAwMDAwMDAwMDAwMSI6MywiMC44MzMiOjIsIjAuODM0Ijo0LCIwLjgzNSI6NCwiMC44MzYiOjAsIjAuODM3Ijo4LCIwLjgzOCI6MiwiMC44MzkiOjIsIjAuODQiOjcsIjAuODQxIjo0LCIwLjg0MiI6MiwiMC44NDMiOjYsIjAuODQ0Ijo2LCIwLjg0NSI6MywiMC44NDYiOjQsIjAuODQ3Ijo1LCIwLjg0OCI6MSwiMC44NDkiOjIsIjAuODUiOjUsIjAuODUxIjoxLCIwLjg1MiI6NiwiMC44NTMiOjYsIjAuODU0IjozLCIwLjg1NSI6NCwiMC44NTYiOjUsIjAuODU3IjozLCIwLjg1OCI6MywiMC44NTkiOjcsIjAuODYiOjUsIjAuODYxIjoxLCIwLjg2MiI6MywiMC44NjMiOjcsIjAuODY0IjozLCIwLjg2NSI6MywiMC44NjYiOjQsIjAuODY3Ijo0LCIwLjg2OCI6NiwiMC44NjkiOjIsIjAuODciOjYsIjAuODcxIjo3LCIwLjg3MiI6OSwiMC44NzMiOjEsIjAuODc0IjozLCIwLjg3NSI6OCwiMC44NzYiOjIsIjAuODc3IjozLCIwLjg3OCI6NywiMC44NzkiOjUsIjAuODgiOjYsIjAuODgxIjo3LCIwLjg4MiI6NiwiMC44ODMiOjgsIjAuODg0Ijo3LCIwLjg4NSI6MiwiMC44ODYiOjEsIjAuODg3Ijo3LCIwLjg4OCI6NCwiMC44ODkiOjYsIjAuODkiOjMsIjAuODkxIjo3LCIwLjg5MiI6NCwiMC44OTMiOjYsIjAuODk0Ijo3LCIwLjg5NSI6NywiMC44OTYiOjYsIjAuODk3Ijo2LCIwLjg5OCI6NywiMC44OTkiOjEwLCIwLjkiOjQsIjAuOTAxIjo4LCIwLjkwMiI6MTEsIjAuOTAzIjoyLCIwLjkwNCI6NiwiMC45MDUiOjUsIjAuOTA2Ijo1LCIwLjkwNyI6OSwiMC45MDgiOjEwLCIwLjkwOSI6NywiMC45MSI6NiwiMC45MTEiOjEwLCIwLjkxMiI6NSwiMC45MTMiOjUsIjAuOTE0Ijo1LCIwLjkxNSI6NiwiMC45MTYiOjksIjAuOTE3Ijo5LCIwLjkxOCI6NywiMC45MTkiOjExLCIwLjkyIjoxMCwiMC45MjEiOjUsIjAuOTIyIjo3LCIwLjkyMyI6OCwiMC45MjQiOjE3LCIwLjkyNSI6OSwiMC45MjYiOjExLCIwLjkyNyI6MTIsIjAuOTI4IjoxMSwiMC45MjkiOjEwLCIwLjkzIjoxMywiMC45MzEiOjksIjAuOTMyIjoxMSwiMC45MzMiOjEwLCIwLjkzNCI6MTIsIjAuOTM1IjoxNCwiMC45MzYiOjQsIjAuOTM3Ijo5LCIwLjkzODAwMDAwMDAwMDAwMDEiOjExLCIwLjkzOTAwMDAwMDAwMDAwMDEiOjEwLCIwLjk0MDAwMDAwMDAwMDAwMDEiOjEwLCIwLjk0MTAwMDAwMDAwMDAwMDEiOjE1LCIwLjk0MjAwMDAwMDAwMDAwMDEiOjgsIjAuOTQzMDAwMDAwMDAwMDAwMSI6OSwiMC45NDQwMDAwMDAwMDAwMDAxIjoxMCwiMC45NDUwMDAwMDAwMDAwMDAxIjo5LCIwLjk0NjAwMDAwMDAwMDAwMDEiOjE1LCIwLjk0NzAwMDAwMDAwMDAwMDEiOjEwLCIwLjk0ODAwMDAwMDAwMDAwMDEiOjExLCIwLjk0OTAwMDAwMDAwMDAwMDEiOjgsIjAuOTUwMDAwMDAwMDAwMDAwMSI6OCwiMC45NTEwMDAwMDAwMDAwMDAxIjoxNywiMC45NTIwMDAwMDAwMDAwMDAxIjoxOSwiMC45NTMwMDAwMDAwMDAwMDAxIjoxNiwiMC45NTQwMDAwMDAwMDAwMDAxIjoxNSwiMC45NTUwMDAwMDAwMDAwMDAxIjoxNSwiMC45NTYwMDAwMDAwMDAwMDAxIjoxNCwiMC45NTcwMDAwMDAwMDAwMDAxIjoxMywiMC45NTgwMDAwMDAwMDAwMDAxIjoxMSwiMC45NTkwMDAwMDAwMDAwMDAxIjoyMCwiMC45NiI6MTQsIjAuOTYxIjoxNSwiMC45NjIiOjE1LCIwLjk2MyI6MjcsIjAuOTY0IjoxOCwiMC45NjUiOjE1LCIwLjk2NiI6MTQsIjAuOTY3IjoxOCwiMC45NjgiOjI0LCIwLjk2OSI6MjUsIjAuOTciOjI2LCIwLjk3MSI6MTQsIjAuOTcyIjoyNCwiMC45NzMiOjM0LCIwLjk3NCI6MzcsIjAuOTc1IjozMiwiMC45NzYiOjM0LCIwLjk3NyI6MjMsIjAuOTc4IjoyNiwiMC45NzkiOjQ1LCIwLjk4Ijo0NSwiMC45ODEiOjM0LCIwLjk4MiI6MzgsIjAuOTgzIjo1NiwiMC45ODQiOjYwLCIwLjk4NSI6NjYsIjAuOTg2Ijo2MCwiMC45ODciOjc4LCIwLjk4OCI6OTAsIjAuOTg5IjoxMTEsIjAuOTkiOjExMSwiMC45OTEiOjEzNCwiMC45OTIiOjE3MCwiMC45OTMiOjE3MywiMC45OTQiOjMwMywiMC45OTUiOjM1NSwiMC45OTYiOjYwNywiMC45OTciOjEzNjcsIjAuOTk4IjoxMDA0NCwiMC45OTkiOjM1NjI4fSwiZGlzYWJsZWQiOmZhbHNlLCJvcmRlciI6ImRlc2MifV0&viewMode=annotate&pagination=eyIkaWQiOm51bGwsImlkIjpudWxsLCJzaXplIjoxLCJwYWdlIjoxLCJwYWdlU2l6ZU9wdGlvbnMiOlsxLDEwLDIwLDUwLDEwMF0sIm1heFJlY29yZHNMaW1pdCI6MTAwMDAsImRpc2FibGVkU2hvcnRDdXRQYWdpbmF0aW9uIjpmYWxzZX0) for last night's version of `AlpacaCleaned` (login with argilla/1234).

We plan to spend some more time labeling and contributing back to this project. My question is if it would be possible to share a set of flagged records (with positional ids as in the original json) with you to make sure we edit them in the right way. For example, what do with requests related to attached photos, paintings, and so on.

**Comment by gururise** [comment]
Hello @dvsrepo 

Thats very interesting what you've done so far. I would definitely be open to sharing a set of flagged records to further improve coordination.

**Comment by gururise** [comment]
I've incorporated the alpaca-garbage-collector-multilingual model into the gradio gui.
