### ISSUE TITLE
Is there a boost in performance for full fine-tuning versus LoRA?

### ISSUE THREAD

**Issue by timothylimyl** [gururise/AlpacaDataCleaned#56]
It seems that the evaluation comparison made was all under the training scheme of LoRA. Any ideas on full fine-tuning versus the LoRA approach?

**Comment by gururise** [comment]
No idea how well the full fine-tuned models work.  They could perform better. You can test on academic benchmarks using lm-eval-harness to get some idea; however, what we really need is a way to test conversational ability in a chatbot.

**Comment by Wheeledparasite** [comment]
Training on the latest version of this dataset results in a very capable alpaca model.  I'm seeing much better results than with the original alpaca dataset.
