### ISSUE TITLE
Is the "alpaca_data_cleaned_archive.json" file having all cleaned data?

### ISSUE THREAD

**Issue by Bigggapple** [gururise/AlpacaDataCleaned#60]
I just want to confirm the content of the file "alpaca_data_cleaned_archive.json".  I found "alpaca_data_cleaned.json" is 44.3M, while "alpaca_data_cleaned_archive.json" is only 22.5M. Based on my understanding, the second file should combine all the cleaned data from the first one with the remaining replaced by the outputs generated by GPT-4. Therefore, the size of these two files should be similar and the "alpaca_data_cleaned_archive.json" might make llama get better results after the fine-tuning. Is that right?

**Comment by gururise** [comment]
**alpaca_data_cleaned_archive.json** is based on the original alpaca dataset with all the curated fixes.  The **alpaca_data_cleaned.json** is the latest dataset that includes **ALL** the human fixes from the original dataset along with the remaining (uncleaned) prompts merged with the GPT4 dataset.

It is recommended to use the **alpaca_data_cleaned.json**, as it includes both the human curated fixes and the merged GPT4 dataset.  Ie. it is basically a cleaned/curated version of the GPT4-LLM dataset.

**Comment by Bigggapple** [comment]
> 
Oh, I get it now. Thank you for clarifying that for me.
